version: 2
updates:
  - package-ecosystem: 'github-actions'
    directories:
      - '/.github/actions/**/*'
      - '/.github/workflows/**/*'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'ci(github)'
    ignore:
      - dependency-name: '*'
        # ignore patch updates due to frequency
        update-types: ['version-update:semver-patch']
